/* list of common pokemon for the PokemonSelect component. */
const pokemon = [
    "pikachu",
    "jigglypuff",
    "charizard",
    "gengar",
    "arcanine",
    "bulbasaur",
    "blaziken",
    "umbreon",
    "lucario",
    "gardevoir",
    "eevee",
    "dragonite",
    "absol",
    "typhlosion",
    "ampharos",
    "squirtle",
    "flygon",
    "ninetales",
    "tyranitar",
    "infernape",
    "snorlax",
    "torterra",
    "luxray",
    "scizor",
    "blastoise",
    "mudkip",
    "garchomp",
    "lapras",
    "mewtwo",
    "articuno",
    "mew",
    "rattata",
    "magikarp",
    "mewtwo",
    "eeveelution",
    "rayquaza",
    "entei",
    "suicune",
    "raikou",
    "ho-oh",
    "lugia",
    "celebi",
    "entei",
    "suicune",
    "ho-oh",
    "lugia",
    "celebi",
    "entei",
    "suicune",
    "raikou",
    "ho-oh",
    "lugia",
    "celebi",
    "entei",
    "suicune",
    "raikou",
    "ho-oh",
    "lugia",
    "celebi",
  ];
  
  
  export default pokemon;
  